skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    # Pip builds
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    # Conda builds
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
      SCIPY: "0.18"
      NUMPY: "1.11"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"


platform:
    - x64

build_script:
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - SET OPENBLAS_NUM_THREADS=1
  - If Defined PY_MAJOR_VER ( call tools\ci\appveyor_conda.bat ) else ( call tools\ci\appveyor_pip.bat )
  - pip install "pytest<4" pytest-xdist
  - python setup.py develop

test_script:
  - pytest -n 2 -r a statsmodels
