skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  PYTEST_DIRECTIVES: --skip-slow
  matrix:
    # Pip builds
    - PYTHON: C:\Python27
      PYTEST_DIRECTIVES:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
      PYTEST_DIRECTIVES:
    # Conda builds
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
      SCIPY: "0.18"
      NUMPY: "1.11"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"


platform:
    - x64

build_script:
  # Show information about CPU running job to understand BLAS issues
  - wmic cpu get caption, name, numberofcores
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - SET OPENBLAS_NUM_THREADS=1
  - If Defined PY_MAJOR_VER ( call tools\ci\appveyor_conda.bat ) else ( call tools\ci\appveyor_pip.bat )
  - pip install pytest pytest-xdist
  - python setup.py develop

test_script:
  # Remove xdist until warning reporting is working
  - echo pytest -n auto -r s statsmodels --skip-examples %PYTEST_DIRECTIVES%
  - pytest -n auto -r s statsmodels --skip-examples %PYTEST_DIRECTIVES%
