[build-system]
# These are strictly build requirements. Runtime requirements are listed in
# INSTALL_REQUIRES in setup.py
requires = [
    "setuptools>=59.2.0",
    "wheel>=0.37.1",
    "cython>=0.29.26,<3",  # Sync with CYTHON_MIN_VER in setup
    "oldest-supported-numpy",
    "numpy; python_version>='3.11'",
    "scipy>=1.4,!=1.9.2",
    "scipy>=1.4,!=1.9.2; sys_platform == \"win32\"",  # Blacklist 1.9.2 due to Windows issues
    "setuptools_scm[toml]>=6.4.2,<7.0.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "statsmodels/_version.py"
