[build-system]
requires = [
    "setuptools>=59.2.0",
    "wheel>=0.37.1",
    "cython>=0.29.32,<3",  # Sync with CYTHON_MIN_VER in setup
    # Workaround for oldest supported numpy using 1.21.6, but SciPy 1.9.2+ requiring 1.22.3+
    "oldest-supported-numpy; python_version!='3.10' or platform_system!='Windows' or platform_python_implementation=='PyPy'",
    "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
    "numpy; python_version>='3.12'",
    "scipy>=1.3",
    "setuptools_scm[toml]>=7.0,<8"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "statsmodels/_version.py"
