# Attributed to NumPy via https://github.com/numpy/numpy/pull/25894
# https://github.com/numpy/numpy/blob/d2d2c25fa81b47810f5cbd85ea6485eb3a3ffec3/.github/workflows/emscripten.yml
name: Test Emscripten/Pyodide build

on:
  # TODO: remove after ready to merge
  push:
    # branches: [ 'main']
  pull_request:
    # branches: [ 'main' ]
  workflow_dispatch:

# Cancel intermediate runs if a new run is queued
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-wasm-emscripten:
    name: Build statsmodels distribution for Pyodide
    runs-on: ubuntu-latest
    env:
      PYODIDE_VERSION: 0.26.1
      # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
      # The appropriate versions can be found in the Pyodide repodata.json
      # "info" field, or in Makefile.envs:
      # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
      PYTHON_VERSION: 3.12.1
      EMSCRIPTEN_VERSION: 3.1.58
      NODE_VERSION: 20
    steps:
    - name: Checkout statsmodels
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

    - name: Build and test statsmodels for Pyodide
      uses: pypa/cibuildwheel@v2.19.1
      env:
        CIBW_PLATFORM: pyodide
        CIBW_BEFORE_BUILD: |
          EMSDK="/home/runner/.cache/cibuildwheel/emsdk-3.1.58/emsdk-3.1.58/upstream/emscripten"
          patch -d $EMSDK/src/ -p1 < {project}/tools/ci/emscripten/0001-load-dependent-libs-globally.patch
        CIBW_TEST_REQUIRES: "pytest pytest-cov matplotlib"
        CIBW_TEST_COMMAND: python -c "import statsmodels as sm; sm.test(['-ra', '--skip-examples', '--skip-slow'], exit=True)"

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: cp312-pyodide_wasm32
        path: ./wheelhouse/*.whl
